version: "3"

services:
  website:
    build: .
    restart: always
    command: sh -c "python manage.py makemigrations &&
                python manage.py migrate &&
                gunicorn cars_api.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file: .env
    
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data/
    env_file: .env

volumes:
  dbdata:

  